#yelp
YELP_CONSUMER_KEY = 'Hm_oV4XnA0QEUO8-qLcHtQ'
YELP_CONSUMER_SECRET = 'iiwCHWXOC8pxZnco9XVEwj487jk'
YELP_TOKEN = 'ZHufKed3bRQPIL-OJpanWWhkoYjE1oWx'
YELP_TOKEN_SECRET = '3Ay9pO1RF58icYrJe78xaRSvkeA'